build_test:
  stage: build
  before_script:
    - apt-get update -qq && apt-get install -y -qq cmake ncurses
  script:
    - if [ -d build ]; then rm -rf build ; fi
    - mkdir build
    - cd build ; cmake generate -G Ninja .. ; ninja all basecode-configured
    - cd tests ; ./tests.sh
