build_test:
  stage: build
  script:
    - if [ -d build ]; then rm -rf build ; fi
    - mkdir build
    - cd build ; cmake generate -G Ninja .. ; ninja all basecode-configured
    - cd tests ; ./tests.sh
