build_test:
  stage: build
  before_script:
    - apt-get update -qq && apt-get install -y -qq libncurses-dev
    - git clone https://github.com/Kitware/CMake.git
    - cd CMake && git checkout v3.13.2
    - ./bootstrap && make && sudo make install
  script:
    - if [ -d build ]; then rm -rf build ; fi
    - mkdir build
    - cd build ; cmake generate -G Ninja .. ; ninja all basecode-configured
    - cd tests ; ./tests.sh
